### ISSUE TITLE
Question about adding schema to the hdfs

### ISSUE THREAD

**Issue by raymerta** [mikegeo98/Grid-5000-TPC-H-over-HDFS-Spark#1]
Hi, I am trying to port your work into enoslib script and I am having question on this part: `hdfs dfs -copyFromLocal /path/to/schema /user`. How do you generate this schema? I checked the Python scripts and it's the csv version or .tbl files?

**Comment by mikegeo98** [comment]
Hello,

You are right, I had not uploaded the files I used to generate the schema, you can find them now in the schema folder : https://github.com/mikegeo98/Grid-5000-TPC-H-over-HDFS-Spark/tree/main/schema

The tbl files are generated using the dbgen scripts, and then Spark SQL queries access the tbl files using the csv schema that I uploaded.

Feel free to ask me anything else :)

Michalis

**Comment by raymerta** [comment]
Awesome! Thanks for the files. I will try it :)
